version: "3.8"
services:
    db1:
        build: ./container
        environment:
            SA_PASSWORD: "AbcY123!"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
            INIT_SCRIPT: "ag_primary.sql"
            INIT_WAIT: 30
        ports:
            - "1535:1433"
            - "1540:1540"            
        container_name: db1
        hostname: db1
        volumes:
            - mssql-server-shared:/var/opt/mssql/shared
            - mssql-server-backup:/var/opt/mssql/backup
        networks:
            - agnetwork
    db2:
        build: ./container
        environment:
            SA_PASSWORD: "AbcY123!"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
            INIT_SCRIPT: "ag_secondary.sql"
            INIT_WAIT: 50
        ports:
            - "1635:1433"
        container_name: db2
        hostname: db2
        volumes:
            - mssql-server-shared:/var/opt/mssql/shared
            - mssql-server-backup:/var/opt/mssql/backup
        networks:
            - agnetwork
    db3:
        build: ./container
        environment:
            SA_PASSWORD: "AbcY123!"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
            INIT_SCRIPT: "ag_secondary.sql"
            INIT_WAIT: 50
        ports:
            - "1735:1433"
        container_name: db3
        hostname: db3
        volumes:
            - mssql-server-shared:/var/opt/mssql/shared
            - mssql-server-backup:/var/opt/mssql/backup
        networks:
            - agnetwork
volumes:
    mssql-server-shared:
    mssql-server-backup:
networks:
    agnetwork: